# Site settings
#theme: jekyll-theme-cayman
title: Population Genetics
author: Adrián Gómez
github_username: adriangeerre

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
